# SPDX-FileCopyrightText: 2026 Darkula contributors
# SPDX-License-Identifier: AGPL-3.0-only
"""BlackGate v1 scenario-structure and golden-rendering tests (PR 6).

Golden hashes are frozen intentionally, not regenerated by tests: changing
canonical observable content or rendering requires a deliberate version
bump and an intentional golden update.
"""

from __future__ import annotations

import hashlib

from tests.unit.testing.fake_world.helpers import (
    LOGIN_PASSWORD,
    LOGIN_USERNAME,
    canonical_scenario,
    fresh_renderer,
    get,
    login,
)

from darkula.testing.fake_world import (
    RenderedSourceResponse,
    Visibility,
    get_scenario,
)
from darkula.testing.fake_world.identifiers import BehaviorId, SourceId

#: Frozen SHA-256 of canonical page bodies (golden-rendering policy).
LANDING_SHA256 = "ebd5f067824a09a8b43a2712985a66e9ba1c149b76f1adc3877a53f57edf4c9e"
LOGIN_PAGE_SHA256 = "a47000ac99f0c1315fbc03e42f95cd3838c0fc14c13ba6a2a2f28d9e4a5b20d9"
BOARD_INDEX_SHA256 = "a093d15014143c676b4ef96b5a1c2a2f3d7d6bb95fed6e91da4f3261e2ca8213"
THREAD_PAGE1_SHA256 = "640e96a21142780765fabe6a88cf57051393cbf35727f3340111c805a52c2104"
ATTACHMENT_BODY_SHA256 = (
    "55ab6cd9466af8ada0a4269ff1bd387e34d4aa289ea2b5b23c0bbec904e8097d"
)


class TestBlackGateStructure:
    """Canonical scenario structure required by PR 6 acceptance criteria."""

    def test_two_or_more_boards(self) -> None:
        boards = canonical_scenario().sources[0].boards
        assert len(boards) >= 2
        assert [b.name for b in boards] == [
            "Announcements",
            "Access & Credentials",
            "Off-Topic Chatter",
            "Archives",
        ]

    def test_paginated_thread_exists(self) -> None:
        scenario = canonical_scenario()
        thread = scenario.find_thread("thr-hospital-creds")
        per_page = scenario.sources[0].policy.posts_per_page
        assert per_page == 10
        assert len(thread.posts) == 12
        import math

        assert math.ceil(len(thread.posts) / per_page) == 2

    def test_public_preview_and_protected_content_both_exist(self) -> None:
        scenario = canonical_scenario()
        source = scenario.sources[0]
        public = [
            t
            for b in source.boards
            for t in b.threads
            if t.visibility == Visibility.PUBLIC
        ]
        protected = [
            t
            for b in source.boards
            for t in b.threads
            if t.visibility in (Visibility.REGISTERED, Visibility.AUTHENTICATED)
        ]
        assert public and protected

    def test_every_major_realism_object_present(self) -> None:
        scenario = canonical_scenario()
        posts = scenario._all_posts()
        by_id = {p.post_id.value: p for p in posts}
        assert by_id["p-host-creds-2"].quote is not None  # quote
        assert by_id["p-host-creds-4"].edited_at is not None  # edit
        assert by_id["p-host-creds-6"].deleted  # deletion
        hostile = by_id["p-host-creds-3"].content
        assert "IGNORE ALL PREVIOUS INSTRUCTIONS" in hostile
        multilingual = by_id["p-host-creds-7"].content
        assert any(ord(ch) > 127 for ch in multilingual)
        dup_text = by_id["p-host-creds-5"].content
        assert "mcgh-masoncreek.mgmt.local" in by_id["p-host-creds-1"].content
        assert "mcgh-masoncreek.mgmt.local" in dup_text

    def test_attachments_include_all_required_kinds(self) -> None:
        scenario = canonical_scenario()
        attachments = scenario.sources[0].attachments
        filenames = {a.filename for a in attachments}
        assert "mason_creek_general_qa.txt" in filenames
        assert "../../secrets/domain_backup_v2.zip" in filenames
        assert "network_topology.gif" in filenames
        assert "listing.info" in filenames
        assert any(a.body is None for a in attachments)
        assert any(a.media_type == "image/gif" for a in attachments)

    def test_geo_seed_posts_exist_nowhere_else(self) -> None:
        scenario = canonical_scenario()
        hospital = scenario.find_post("p-host-creds-1").content
        assert "Mason Creek General Hospital (Mason Creek, Washington)" in hospital
        dc = scenario.find_post("p-dc-1").content
        assert "Washington, D.C." in dc
        assert "Mason Creek" not in dc

    def test_synthetic_credentials_clearly_test_only(self) -> None:
        policy = canonical_scenario().sources[0].policy
        assert policy.login_username == LOGIN_USERNAME
        assert policy.login_password == LOGIN_PASSWORD
        assert policy.login_password.endswith("-password")
        assert get_scenario("blackgate-core", version=1).sources[0].policy is policy

    def test_rate_limited_board_and_failing_thread_configured(self) -> None:
        scenario = canonical_scenario()
        archives = scenario.find_board("board-archives")
        assert archives.rate_limit is not None
        assert archives.rate_limit.max_views_per_session == 2
        assert archives.rate_limit.retry_after_seconds == 60
        intros = scenario.find_thread("thr-intros")
        assert intros.failure_schedule is not None
        assert intros.failure_schedule.status_code == 503

    def test_exactly_one_registered_scenario_v1(self) -> None:
        from darkula.testing.fake_world.registry import list_scenarios

        scenarios = list_scenarios()
        assert len(scenarios) == 1
        assert scenarios[0].scenario_id.value == "blackgate-core"
        assert scenarios[0].scenario_version.value == 1


class TestCanonicalGoldenPages:
    """Small set of frozen canonical page hashes (avoid brittle snapshots)."""

    def _sha(self, body: bytes) -> str:
        return hashlib.sha256(body).hexdigest()

    def _render_thread_page_1(self) -> RenderedSourceResponse:
        renderer = fresh_renderer()
        scenario = canonical_scenario()
        session = login(renderer, scenario)
        return get(renderer, scenario, "/thread/thr-hospital-creds", session=session)

    def test_golden_landing_login_board_thread_attachment(self) -> None:
        scenario = canonical_scenario()
        renderer = fresh_renderer()
        assert self._sha(get(renderer, scenario, "/").body) == LANDING_SHA256
        assert self._sha(get(renderer, scenario, "/login").body) == LOGIN_PAGE_SHA256

        session = login(renderer, scenario)
        assert self._sha(get(renderer, scenario, "/index", session=session).body) == (
            BOARD_INDEX_SHA256
        )
        thread_page = self._render_thread_page_1()
        assert self._sha(thread_page.body) == THREAD_PAGE1_SHA256

        attachment = get(
            renderer,
            scenario,
            "/attachment/att-cred-list",
            session=session,
        )
        assert self._sha(attachment.body) == ATTACHMENT_BODY_SHA256

    def test_golden_hashes_are_stable_across_instances(self) -> None:
        scenario = canonical_scenario()
        renderer = fresh_renderer()
        assert self._sha(get(renderer, scenario, "/").body) == LANDING_SHA256

    def test_no_large_blob_snapshots_required(self) -> None:
        # Golden policy: hashes + semantic fragment assertions only. The
        # canonical test suite must never rewrite these hashes implicitly.
        assert len(LANDING_SHA256) == 64

    def test_behavior_ids_covered_by_threat_census(self) -> None:
        scenario = canonical_scenario()
        manifest = scenario.traceability
        assert manifest is not None
        expected = {
            "FW-BG-AUTH-001",
            "FW-BG-AUTH-002",
            "FW-BG-AUTH-003",
            "FW-BG-AUTH-004",
            "FW-BG-AUTH-005",
            "FW-BG-AUTH-006",
            "FW-BG-PAGE-001",
            "FW-BG-PAGE-002",
            "FW-BG-PAGE-003",
            "FW-BG-PAGE-004",
            "FW-BG-PAGE-005",
            "FW-BG-PAGE-006",
            "FW-BG-EDIT-001",
            "FW-BG-DELETE-001",
            "FW-BG-QUOTE-001",
            "FW-BG-DUP-001",
            "FW-BG-MULTI-001",
            "FW-BG-MALFORMED-001",
            "FW-BG-HOSTILE-001",
            "FW-BG-ATTACH-001",
            "FW-BG-ATTACH-002",
            "FW-BG-ATTACH-003",
            "FW-BG-GEO-001",
            "FW-BG-GEO-002",
            "FW-BG-REDIRECT-001",
            "FW-BG-RATE-001",
            "FW-BG-FAIL-001",
            "FW-BG-TRUTH-001",
        }
        actual = {str(e.behavior_id) for e in manifest.entries}
        assert actual == expected

    def test_behavior_id_convention_enforced(self) -> None:
        scenario = canonical_scenario()
        manifest = scenario.traceability
        assert manifest is not None
        for entry in manifest.entries:
            assert BehaviorId(str(entry.behavior_id)) == entry.behavior_id


class TestSourceIdentityVsPresentation:
    def test_source_id_semantic_not_url(self) -> None:
        source = canonical_scenario().sources[0]
        assert source.source_id == SourceId("blackgate")
        assert source.base_domain == "blackgate.example.test"
        assert ":" not in source.base_domain  # no URL, just a domain hint
